# Project information
site_name: My RPi HomeLab
site_author: Gino Cicatiello
site_description: >-
  How to build up a "domestic" homelab with raspberry pi's

# Repository
repo_name: ginocic/PiHomeLab
repo_url: https://github.com/ginocic/PiHomeLab

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/ginocic"  target="_blank" rel="noopener">Gino Cicatiello</a>

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - toc.follow
  #   - search.suggest
  #   - search.highlight
  #   - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select

# Plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Europe/Amsterdam
      locale: en
      type: iso_date
  - search
#   - tags
#   - glightbox:
#       zoomable: true
#       draggable: true
#       skip_classes:
#         - skip-lightbox

# Hooks
#hooks:

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ginocic
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Github
        checked: false
#   tags:
#     HTML5: html
#     JavaScript: js
#     CSS: css

# Extensions
markdown_extensions:
#   - def_list
  - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - 'Operating System':
    - Installation: os/installation.md
