# Project information
site_name: My HomeLab
site_author: Gino Cicatiello
site_description: >-
  How to build up a "domestic" homelab

# Repository
repo_name: ginocic/PiHomeLab
repo_url: https://github.com/ginocic/PiHomeLab

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/ginocic"  target="_blank" rel="noopener">Gino Cicatiello</a>

# Configuration
theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: deep orange
    accent: amber
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.top
    - toc.follow
  #   - search.suggest
  #   - search.highlight

# Plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: Europe/Amsterdam
      locale: en
      type: iso_date
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: false
  - search
#   - tags
#   - glightbox:
#       zoomable: true
#       draggable: true
#       skip_classes:
#         - skip-lightbox

# Hooks
#hooks:

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ginocic
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Github
        checked: false
#   tags:
#     HTML5: html
#     JavaScript: js
#     CSS: css

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
#   - def_list
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - Operating System:
    - Installation: os/installation.md
    - Connection over SSH: os/ssh.md
    - Mandatory steps:
      - Raspberry Pi:
        - Move the Raspberry PI root file system to a USB drive: mandatory/rpi/rootfs.md
        - Enabling the TRIM function: mandatory/rpi/fstrim.md
        - Networking: mandatory/rpi/networking.md
      - MiniPC:
        - Sudo and Sudoers: mandatory/minipc/sudo.md
        - Networking: mandatory/minipc/networking.md
      - All System: mandatory/all.md
    - Customization: os/customization.md
