site_name: My RPi HomeLab
repo_url: https://github.com/ginocic/PiHomeLab

nav:
  - Home: index.md
  - 'Operating System':
    - Installation: os/installation.md

theme:
  name: material
  language: en

  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    # - toc.integrate
    - toc.follow
  #   - search.suggest
  #   - search.highlight
  #   - content.tabs.link
  #   - content.code.annotate
  #   - content.code.copy

# markdown_extensions:
#   - def_list
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - pymdownx.keys
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ginocic
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Github
        checked: false
#   tags:
#     HTML5: html
#     JavaScript: js
#     CSS: css

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-committers:
  #     repository: ginocic/PiHomeLab
  #     branch: main
  - git-authors
#   - search
#   - tags
#   - glightbox:
#       zoomable: true
#       draggable: true
#       skip_classes:
#         - skip-lightbox

copyright: |
  &copy; 2024 <a href="https://github.com/ginocic"  target="_blank" rel="noopener">Gino Cicatiello</a>